### ISSUE TITLE
[feature request] adjustable 1hr circle

### ISSUE THREAD

**Issue by natestemen** [nate-parrott/subway#2]
Was recently looking for apartments and wanted to find one that was <=30 min away from where I work. This would be a great tool to help find neighborhoods where the commute would satisfy a certain time constraint. Perhaps, like you have the 1hr circle, you could allow the user to input a time and it would draw a new circle or highlight the stops within 30 min.

**Comment by nate-parrott** [comment]
Just added a 30-minute mark! (might have to clear your cache to see it)

A user-adjustable circle is a bit complicated, since the 1-hr circle (and its label) are baked into an SVG right now that's loaded into the document. But I'll definitely consider it!

**Comment by natestemen** [comment]
Awesome, thanks Nate!
